blog/urls.py
from django.urls import path

from .views import render_posts, post_detail

app_name= 'blog'
urlpatterns =[
    path('',render_posts,name='posts'),
    path('<int:post_id>',post_detail,name="post_detail") #esto es para cuando se le pasa un id en el navegador
]

django_portafolio_simple/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from portfolio import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home,name='home'),
    path('blog/',include('blog.urls'))
]
urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

blog/models.py
from django.db import models
import datetime
# Create your models here.



class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    image = models.ImageField(upload_to='blog/images')
    date = models.DateField(datetime.date.today)

portfolio/models.py
from django.db import models
from django.db.models import ImageField
from django.db.models.fields import CharField, URLField

# Create your models here.


class Project(models.Model):
    title =  CharField(max_length=100)
    description = CharField(max_length=250)
    image = ImageField(upload_to='portfolio/images')
    url = URLField(blank=True)

blog/views.py
from django.shortcuts import render, get_object_or_404
from .models import Post
# Create your views here.

def render_posts(request):
    posts = Post.objects.all()# esto es para obtener todos los objetos de tipo Post
    return render(request,'posts.html',{'posts':posts})

def post_detail(request,post_id):
    post=get_object_or_404(Post,pk=post_id) #aca obetenemos el objecto con su pk (id)
    return render(request,'post_detail.html',{"post":post})

portfolio/views.py
from django.shortcuts import render

# Create your views here.
from portfolio.models import Project #asi se tiene que importar de manera correcta un modelo


def home(request):
   projects = Project.objects.all() #esta variable almacena todos los proyectos del objeto
   return render(request, 'home.html',{'projects':projects})

blog/templates/post_detail.html
{% extends 'layout.html' %}

{% block content%}
<h1>POSTS</h1>

<h2>{{ post.title }}</h2>
    <h3>{{ post.date }}</h3>
    <p>{{ post.description }}</p>
    <img src="{{ post.image.url}}" alt="{{ post.title}}">





{% endblock %}

blog/templates/posts.html
{% extends 'layout.html' %}


{% block content%}

<h1>Posts</h1>

{% for post in posts %}
    <h2>{{ post.title }}</h2>
    <p>{{ post.description| truncatechars:100 }}</p>
    <p>{{ post.date|date:'M d Y' }}</p>
    <img src="{{ post.image.url}}" alt="{{ post.title}}">

    <a href="{% url 'blog:post_detail' post.id %}">{{ post.title }}</a>
{% endfor %}



{% endblock %}

portfolio/templates/home.html
{% extends 'layout.html' %}

{% block content %}
 {% load static %}

    <header class="row bg-black">
    <div class="col-md-4">
        <img src="{%static 'portfolio/profile.jpg' %}" class="img-fluid img-thumbnail">
    </div>

    <div class="col-md-8 my-auto">
        <h1>Soy raul ortiz</h1>
        <h3>soy desarrollador backend con python</h3>
        <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ipsum dolor sit amet consectetur adipiscing elit ut aliquam purus. Integer enim neque volutpat ac tincidunt vitae semper. Leo in vitae turpis massa. Velit egestas dui id ornare arcu odio. Porttitor lacus luctus accumsan tortor. Hac habitasse platea dictumst quisque. Tellus in hac habitasse platea dictumst vestibulum rhoncus. Turpis egestas integer eget aliquet nibh praesent tristique magna. Fermentum odio eu feugiat pretium nibh ipsum consequat nisl vel. Velit sed ullamcorper morbi tincidunt ornare massa eget.
            Dui accumsan sit amet nulla facilisi morbi tempus. Tristique sollicitudin nibh sit amet commodo nulla facilisi nullam vehicula. Viverra ipsum nunc aliquet bibendum. Nulla facilisi cras fermentum odio eu feugiat. Eu sem integer vitae justo eget magna fermentum. Dictum sit amet justo donec enim diam vulputate ut pharetra. Nulla porttitor massa id neque aliquam. Ullamcorper sit amet risus nullam. Augue eget arcu dictum varius duis at. Viverra justo nec ultrices dui sapien. Duis ut diam quam nulla porttitor. Aliquam etiam erat velit scelerisque in dictum non. Lectus mauris ultrices eros in cursus turpis. A iaculis at erat pellentesque. Sed lectus vestibulum mattis ullamcorper velit sed. Turpis egestas integer eget aliquet nibh praesent tristique magna sit. Nec tincidunt praesent semper feugiat nibh. Donec ultrices tincidunt arcu non sodales. At ultrices mi tempus imperdiet nulla malesuada pellentesque elit eget. Sem integer vitae justo eget magna.</p>
   <a href="https://github.com/RaulOrtiz99" class="btn btn-primary btn-lg rounded-0 my3">Visitar mi Github</a>
    </div>


    </header>

{% for project in projects %}

<h2>{{ project.title }}</h2>
    <h3>{{ project.description }}</h3>
    <div>
    <img src="{{ project.image.url}}" alt="{{ project.title }}">
    </div>
   {% if project.url %}
     <a href="{{ project.url }}">
        <button>{{ project.url }}</button></a>
    {% endif %}

{% endfor %}

 {% endblock %}

portfolio/templates/layout.html
{% load static%}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Django Portafolio</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'main.css'%}">
</head>
<body class="text-light">

    {% include 'partials/navbar.html' %}

   <div class="container p-4">
        {% block content %}=
    {% endblock %}
   </div>


</body>
</html>

portfolio/templates/partials/navbar.html
{% load static %}
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container">
    <a class="navbar-brand fw-bold fst-italic" href="/">Raúl Ortiz</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav ms-auto">

        <li class="nav-item">
          <a class="nav-link" href="{% url 'blog:posts' %}">Blog</a>
        </li>
        <li class="nav-item d-flex align-items-center">
          <a class="btn btn-primary btn-sm" href="{% static 'portfolio/cv.pdf' %}" target="_blank">Download CV</a>
        </li>
      </ul>
    </div>
  </div>
</nav>